apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: php-apache-hpa
  labels:
    app: php-apache-hpa
spec:
  selector:
    matchLabels:
      app: php-apache-hpa
  replicas: 1
  template:
    metadata:
      labels:
        app: php-apache-hpa
    spec:
      containers:
      - name: php-apache-hpa
        image: arthurramires/php-apache-hpa:latest
        ports:
        - containerPort: 80

---        

apiVersion: v1
kind: Service
metadata:
  name: php-apache-hpa-service
  labels:
    app: php-apache-hpa-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: php-apache-hpa
