apiVersion: apps/v1
kind: Deployment
metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app

    spec:
      containers:
      - name: app
        image: docker.io/arthurramires/pesquisas-ricas-server:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

        envFrom:
        - configMapRef:
            name: app-conf

        volumeMounts:
        - name: app-conf
          mountPath: /usr/app/.env
          subPath: .env
        # - name: test-volume
        #   mountPath: /usr/app/tmp
        - name: image-storage
          mountPath: /usr/app/tmp


      volumes:
      - name: app-conf
        configMap:
          name: app-conf
          items:
            - key: env
              path: .env
              volumes:
      - name: image-storage
      #   persistentVolumeClaim:
      #     claimName: nfs
        hostPath:
          path: /tmp
          type: Directory
      # - name: image-storage
      #   persistentVolumeClaim:
      #     claimName: app-pv-claim


