steps:

  - id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f','docker-compose.yaml','up','-d']

  - id: "Rodando npm"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','npm','i']

  - id: "Rodando migrations"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','yarn','sequelize','db:migrate']  
  
  - id: "Building image using Dockerfile"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/app:$SHORT_SHA','-f','Dockerfile','.']
  
  - id: "Pushing image"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/app:$SHORT_SHA']
  
  - id: "Adjusting deployment file - k8s"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app:$SHORT_SHA#g' k8s/app/deployment.yaml > k8s/app/deployment-new.yaml;
        cat k8s/app/deployment-new.yaml
  - id: 'Deploying k8s'
    name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - 'apply'
      - '-f'
      - 'k8s/app/deployment-new.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=pesquisas-ricas'