version: "3"

services:
    app:
        build: .
        container_name: app
        volumes:
            - ./node_modules:/usr/app/node_modules
        environment:
             - APP_URL=http://localhost:3333
             - NODE_ENV=development
             #- MY_POD_NAME=metadata.name
             #- MY_NODE_NAME=spec.nodeName
             - DB_DIALECT=postgres
             - DB_HOST=db
             - DB_USER=postgres
             - DB_PASS=docker
             - DB_NAME=postgres
             - APP_SECRET=737eec44b84c9bc67c816a5c03eb5777
             - REDIS_HOST=redis
             - REDIS_PORT=6379
             - MAIL_HOST=smtp.mailtrap.io
             - MAIL_PORT=2525
             - MAIL_USER=5233970d52909c
             - MAIL_PASS=bf970bde54e15c
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:1.17
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=postgres
        restart: always
        tty: true
        ports:
            - "5432:5432"
        # env_file:
        #     - .env
        volumes:
             - .docker/dbdata:/var/lib/postgresql
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
