apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-server
spec: #spec do deployment
  replicas: 1
  
  selector: # selector utilizado para criar o service
    matchLabels:
      app: postgres-server
      tier: db

  template: # referente ao POD
    metadata:
      labels:
        app: postgres-server
        tier: db
    spec: # spec do POD
      containers:
      - image: postgres
        name: postgres-server

        env:
          - name: POSTGRES_PASSWORD
            value: docker
              
        
        ports:
        - containerPort: 5432

        volumeMounts: #monta o volume efetivamente
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql

      volumes: # definicao do volume
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
        


