apiVersion: apps/v1
kind: Deployment
metadata:
  name: potsgres-server
spec: #spec do deployment
  replicas: 1
  
  selector: # selector utilizado para criar o service
    matchLabels:
      app: potsgres-server
      tier: db

  template: # referente ao POD
    metadata:
      labels:
        app: potsgres-server
        tier: db
    spec: # spec do POD
      containers:
      - image: postgres
        name: potsgres-server
        
        ports:
        - containerPort: 5432

        volumeMounts: #monta o volume efetivamente
        - name: potsgres-persistent-storage
          mountPath: /var/lib/postgresql

      volumes: # definicao do volume
      - name: potsgres-persistent-storage
        persistentVolumeClaim:
          claimName: potsgres-pv-claim
        


