apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app

    spec:
      containers:
      - name: app
        image: gcr.io/pesquisas-ricas-server/app:latest
        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: app-conf

        volumeMounts:
        - name: app-conf
          mountPath: /usr/app/.env
          subPath: .env
        - name: image-storage
          mountPath: /usr/app/tmp


      volumes:
      - name: app-conf
        configMap:
          name: app-conf
          items:
            - key: env
              path: .env
      - name: image-storage
        persistentVolumeClaim:
          claimName: app-pv-claim

