apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: app-hpa
spec:
    maxReplicas: 6
    minReplicas: 2
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: app
    targetCPUUtilizationPercentage: 20
